// all the fields that are represented by values in a Cloudfront realtime log
const logFields = [
  'timestamp',
  'c_ip',
  'time_to_first_byte',
  'sc_status',
  'sc_bytes',
  'cs_method',
  'cs_protocol',
  'cs_host',
  'cs_uri_stem',
  'cs_bytes',
  'x_edge_location',
  'x_edge_request_id',
  'x_host_header',
  'time_taken',
  'cs_protocol_version',
  'c_ip_version',
  'cs_user_agent',
  'cs_referer',
  'cs_cookie',
  'cs_uri_query',
  'x_edge_response_result_type',
  'x_forwarded_for',
  'ssl_protocol',
  'ssl_cipher',
  'x_edge_result_type',
  'fle_encrypted_fields',
  'fle_status',
  'sc_content_type',
  'sc_content_len',
  'sc_range_start',
  'sc_range_end',
  'c_port',
  'x_edge_detailed_result_type',
  'c_country',
  'cs_accept_encoding',
  'cs_accept',
  'cache_behavior_path_pattern',
  'cs_headers',
  'cs_header_names',
  'cs_headers_count',
  'primary_distribution_id',
  'primary_distribution_dns_name',
  'origin_fbl',
  'origin_lbl',
  'asn'
];

// this is a mapping of each realtime log field and its type
const fieldTypes = {
  "timestamp" : "timestr", 
  "c_ip" : "str", 
  "time_to_first_byte" : "float", 
  "sc_status" : "int", 
  "sc_bytes" : "int", 
  "cs_method" : "str", 
  "cs_protocol" : "str",
  "cs_host" : "str", 
  "cs_uri_stem" : "str", 
  "cs_bytes" : "int",
  "x_edge_location" : "str", 
  "x_edge_request_id" : "str", 
  "x_host_header" : "str", 
  "time_taken" : "float", 
  "cs_protocol_version" : "str",
  "c_ip_version" : "str", 
  "cs_user_agent" : "str", 
  "cs_referer" : "str", 
  "cs_cookie" : "str", 
  "cs_uri_query" : "str", 
  "x_edge_response_result_type" : "str", 
  "x_forwarded_for" : "str", 
  "ssl_protocol" : "str", 
  "ssl_cipher" : "str", 
  "x_edge_result_type" : "str", 
  "fle_encrypted_fields": "str", 
  "fle_status" : "str",
  "sc_content_type" : "str", 
  "sc_content_len" : "int", 
  "sc_range_start" : "int", 
  "sc_range_end" : "int", 
  "c_port" : "int", 
  "x_edge_detailed_result_type" : "str", 
  "c_country" : "str", 
  "cs_accept_encoding" : "str",
  "cs_accept" : "str",
  "cache_behavior_path_pattern" : "str",
  "cs_headers" : "str", 
  "cs_header_names" : "str", 
  "cs_headers_count" : "int",
  "primary_distribution_id": "str",
  "primary_distribution_dns_name": "str",
  "origin_fbl": "float",
  "origin_lbl": "float",
  "asn": "int"
};

module.exports = { logFields, fieldTypes }