version: '3.9'

services:
  vector:
    image: amazingjason/canopy-vector:latest
    container_name: vector
    volumes:
      - vector_data:/var/lib/vector
    ports:
      - 8383:8383
  clickhouse:
    image: facelessgladiator/canopy-clickhouse:latest
    container_name: clickhouse
    volumes:
      - db_data:/var/lib/clickhouse
      - db_logs:/var/log/clickhouse-server
    ports:
      - 9000:9000
      - 8123:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  grafana:
    depends_on: clickhouse
    condition: service_healthy
    image: amazingjason/canopy-grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3001:3000

volumes:
  db_data:
  db_logs:
  grafana_data:
  vector_data:
