version: '3.9'

services:
  clickhouse:
    image: facelessgladiator/canopy-clickhouse:latest
    container_name: clickhouse
    volumes:
      - db_data:/var/lib/clickhouse
      - db_logs:/var/log/clickhouse-server
    ports:
      - 9000:9000
      - 8123:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
      interval: 5s
      timeout: 3s
  grafana:
    depends_on: 
      - clickhouse
    image: amazingjason/canopy-grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    user: ':'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  db_data:
  db_logs:
  grafana_data:
  vector_data:
